---
booktitle: Proceedings of The 1st Gaze Meets ML workshop
shortname: GMML
year: '2022'
volume: '210'
start: 2022-12-03
end: 2022-12-03
published: 2023-04-03
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: GMML-2022
month: 0
cycles: false
bibtex_editor: Lourentzou, Ismini and Wu, Joy and Kashyap, Satyananda and Karargyris,
  Alexandros and Celi, Leo Anthony and Kawas, Ban and Talathi, Sachin
editor:
- given: Ismini
  family: Lourentzou
- given: Joy
  family: Wu
- given: Satyananda
  family: Kashyap
- given: Alexandros
  family: Karargyris
- given: Leo Anthony
  family: Celi
- given: Ban
  family: Kawas
- given: Sachin
  family: Talathi
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 1st Gaze Meets ML workshop
    Held in New Orleans, USA on 03 December 2022

  Published as Volume 210 by the Proceedings of Machine Learning Research on 03 April 2023.

  Volume Edited by:
    Ismini Lourentzou
    Joy Wu
    Satyananda Kashyap
    Alexandros Karargyris
    Leo Anthony Celi
    Ban Kawas
    Sachin Talathi

  Series Editors:
    Neil D. Lawrence
date_str: 03 Dec
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v210"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v210
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v210
email: ''
conference:
  name: Annual Conference on Neural Information Processing Systems
  url: https://gaze-meets-ml.github.io/
  location: New Orleans, USA
  dates:
  - 2022-12-03
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v210/NeuripsGaze.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v210/NeuripsGaze.bib
